### ISSUE TITLE
Error with useGltf & Environment in production site

### ISSUE THREAD

**Issue by psegarel** [threlte/threlte#474]
"@threlte/core": "^6.0.0",
"@threlte/extras": "^5.0.1",
"three": "^0.154.0",
"svelte": "^4.0.0",
"@sveltejs/kit": "^1.20.4"

After creating a component from a .glb file, using the npx @threlte/gltf command, I get a 500 error on the production site but not on the local development site.
More specifically, the error happens when refreshing the page, if navigating to the page, there's no error.

I was able to fix the useGltf issue by doing the following

`	let gltf: Promise<any>; 
	if (browser) {
	gltf = useGltf<GLTFResult>('/filename.glb');
	}`

but couldn't use this component in production
`<Environment files="lighting.jpg"/>`

**Comment by grischaerbe** [comment]
Can you share a repository that I can have a look at? I guess it's more of an implementation error, since everything inside `<Canvas>` shouldn't mount on the server in the first place.

**Comment by stella-impact** [comment]
> Can you share a repository that I can have a look at? I guess it's more of an implementation error, since everything inside `<Canvas>` shouldn't mount on the server in the first place.

I have sent you an invitation. Thanks for looking into it! Please check the Services page

**Comment by stella-impact** [comment]
Invitation sent. 
I have deployed the project here:
https://threlte-issue.vercel.app/

There's no issues on the local development site but I get a 500 error on the live one

**Comment by grischaerbe** [comment]
@stella-impact Upon having a look at the repo it seems you missed to [adapt the vite.config.ts file according to the installation guide](https://threlte.xyz/docs/learn/getting-started/installation#configuration). It should work then 👍

**Comment by stella-impact** [comment]
Thanks! 
I remember setting this in earlier projects but clearly forgot on the last one, sorry about that. 
Not sure if it's possible but it would help if an error was raised in case the user forgot to set this config.
