### ISSUE TITLE
Add RTL support for `Text`

### ISSUE THREAD

**Issue by 416d72** [threlte/threlte#78]
It would be great to have support for RTL text like Arabic.
I made a [demo](https://svelte.dev/repl/eea1561941074e6ab75095fe12d7989f) where Arabic text doesn't render.

Please note that drei [supports RTL text](https://drei.pmnd.rs/?path=%2Fstory%2Fabstractions-text--text-ltr-st)

**Comment by grischaerbe** [comment]
fixed in #79

**Comment by 416d72** [comment]
Umm, I just updated [the demo](https://svelte.dev/repl/eea1561941074e6ab75095fe12d7989f) with the newest release , replacing `threlte` with `@threlte/core` or `@threlte/extras` , yet the problem still exists!

**Comment by grischaerbe** [comment]
Ah sorry, I forgot to mention: There's a property `direction` on the component `<Text>` now. It accepts "auto", "ltr" and "rtl".

**Comment by 416d72** [comment]
Still not working unfortunately, I've updated [the demo](https://svelte.dev/repl/eea1561941074e6ab75095fe12d7989f)

Here's a quick screenshot

![image](https://user-images.githubusercontent.com/12211826/179164041-6c1a660b-4f51-49b8-ae1f-ab95769f03e5.png)
